### ISSUE TITLE
minor bug in reporting of alpha?

### ISSUE THREAD

**Issue by simon-dedeo** [mimno/Mallet#139]
Hello Mallet —

I think there may be a minor bug in the recording of alpha on the mallet command line. In particular, say I set the "alpha" for a topic model by the command line:

mallet train-topics --input topic-input.mallet --num-topics 15 --output-doc-topics topic-output.txt  --num-iterations 1000 --alpha 0.333 --output-topic-keys keyset.txt

When I look at keyset.txt, it records the Dirichlet parameter for each topic as 0.0222, i.e., as if when I specified the alpha on the command line, I was specifying the sum of the Dirichlet parameters, not the individual alpha_i. 

However, I'm pretty sure it actually ran with alpha_i=0.333, because (for example) when I look at the entropy of the topic distributions that come out the other side, it is much closer to the expected entropy for alpha_i=0.333.

If I let alpha float (i.e., hyperparameter optimization) the reporting seems correct.

Does this make sense? I may very well be mistaken. I think it would be pretty easy for someone who knows the code to check!

Simon

**Comment by mimno** [comment]
So you're calculating the entropy of the posterior per-document distribution from the `topic-output.txt` file? 

I can't find any problems in how the alpha array is set or document distributions are reported, and the sampling code wouldn't do anything differently depending on alpha optimization.

I'm not surprised entropy went down when you started optimizing alpha. I don't have a good sense of what the entropy of the posterior would be.

**Comment by simon-dedeo** [comment]
Hey David—thank you!

I think what's happening is that I'm dumping in a tiny alpha prior (0.02), but then the documents themselves are saying no, really, we're not that sparse, and overruling the prior much more than I thought. This is why the final topic distributions end up much less sparse (i.e., much higher entropy) than the alpha=0.02 would suggest.

Simon
