### ISSUE TITLE
2.0.9-SNAPSHOT hppc dependency error

### ISSUE THREAD

**Issue by spaniard81** [mimno/Mallet#143]
I recently pulled the mallet 2.0.9 -Snapshot and got the following dependency errors for these imports:

import com.carrotsearch.hppc.DoubleArrayList;
import com.carrotsearch.hppc.IntArrayList;
import com.carrotsearch.hppc.IntObjectHashMap;
import com.carrotsearch.hppc.cursors.ObjectCursor;

<img width="472" alt="mallet209snapshot_dependency-error" src="https://user-images.githubusercontent.com/30657162/46669096-ba0e4900-cbce-11e8-9087-857837259eaa.png">

I find no entry for the hppc artifact in the pom.xml file. 
https://maven-repository.com/artifact/com.carrotsearch/hppc/0.7.2

I have therefore reverted to mallet-2.0.8

**Comment by robchallen** [comment]
fix for this in #148

**Comment by jonaschn** [comment]
@mimno This issue could be closed.
