### ISSUE TITLE
No method definition for sumTypeTopicCounts in DMRTopicModel.java

### ISSUE THREAD

**Issue by nonki1974** [mimno/Mallet#156]
Hi,

I've been using LDA and DMR topic model with mallet.
In development version, it seems that there is no method definition for sumTypeTopicCounts in DMRTopicModel.java.
In stable version, that is defined in ParallelTopicModel.java.

https://github.com/mimno/Mallet/blob/47d690a1669b16a7f133a640a9083cc186a43701/src/cc/mallet/topics/DMRTopicModel.java#L325

How could it be corrected?

**Comment by mimno** [comment]
This is now fixed, thanks for reporting!
