### ISSUE TITLE
Error with assigning initial topics in ParallelTopicModel.java

### ISSUE THREAD

**Issue by clause** [mimno/Mallet#166]
I think there's an issue with assigning initial topics. On [Line 248](https://github.com/mimno/Mallet/blob/032184d5e35ba5bf0d099e9ecb985d4984df1592/src/cc/mallet/topics/ParallelTopicModel.java#L248) the loop index is the size of the topics array.  It should be the length of the token sequence.  Because the topic array has a minimum capacity (currently 2) there are always at least some topics added, even if the document has fewer than 2 tokens.

**Comment by mimno** [comment]
Thank you for spotting this! I fixed this and a few other instances in the topic model. I'm not sure the extra topics were ever being used for anything except reports, but I'm glad this is fixed.
