### ISSUE TITLE
Doesn't PolylingualTopicModel.java include a source about --evaluator-filename?

### ISSUE THREAD

**Issue by i-kohey** [mimno/Mallet#181]
I did `--evaluator-filename` of PolylingualTopicModel, but the evaluator-file was not created.
I checked `PolylingualTopicModel.java` and couldn't find any mention of `--evaluator-filename`.

I want to use PolylingualTopicModel's `--evaluator-filename`.
How do I run the command `--evaluator-filename` in a PolylingualTopicModel on Mallet?

**Comment by mimno** [comment]
Thanks for spotting this! The command option was there but it was never implemented. I've added code to save one evaluator per language. Note that these are monolingual, so you will be able to evaluate the log probability of each language individually, but you will not be able to evaluate log probability for a multi-lingual doc as a whole.

**Comment by i-kohey** [comment]
Thank you so much! I will try to use it.
