### ISSUE TITLE
Can only have 2147483647 (max int) tokens in corpus. 

### ISSUE THREAD

**Issue by UnfinishedArchitect** [mimno/Mallet#182]
I have a pretty large corpus. After filtering out common and rare tokens I end up with 3270690345 words. (Not unique, just counting the total words in the corpus.) 

If I try to use Mallet for topic modelling I get the following output after which nothing else happens (no CPU usage).
```
Mallet LDA: 90 topics, 7 topic bits, 1111111 topic mask
Data loaded.
max tokens: 1214
total tokens: -1024276951
```
The obvious indication that something is wrong is the `total tokens: -1024276951` line. This is an obvious integer overflow as 3270690345 is to large for the signed int that seems to store the number of tokens.

I have tested some values below or above 2147483647 (max int) and every time I am above it fails and when I am below it works. 
```
Mallet LDA: 90 topics, 7 topic bits, 1111111 topic mask
Data loaded.
max tokens: 1145
total tokens: 2147483646
<10> LL/token: -11,88627
<20> LL/token: -10,03233
...
```
I currently try to use as many documents as possible but I cannot train on the full corpus.

This may be a simple fix by changing the datatype of the `total tokens` counter to long but I haven't looked at the internals.

**Comment by mimno** [comment]
Thanks for stress-testing! I've checked in a change for the `totalTokens` variable to a `long`, which goes up to 9 quintillion. I did not change anything else, so individual topics can still not go above 2.1 billion tokens. Anything more would break serialization.

**Comment by UnfinishedArchitect** [comment]
Thank you for the super quick implementation. I already finished my first run with the full corpus :-)
