### ISSUE TITLE
Not clear if `trainingProportions` may be `null`

### ISSUE THREAD

**Issue by dscorbett** [mimno/Mallet#193]
The third parameter of `CRFTrainerByLabelLikelihood#train(InstanceList, int, double[])` is documented as follows:
https://github.com/mimno/Mallet/blob/12487de1aa6433bdcf5af0ee0a17b368e64c7acf/src/cc/mallet/fst/CRFTrainerByLabelLikelihood.java#L182-L184
“If non-null” implies that setting it to `null` is a valid alternative. However, doing so induces a `NullPointerException`. Either the method should treat `null` like `new double[] {1.0}` or the documentation should clarify that `null` is not allowed.

**Comment by mimno** [comment]
I removed the reference to non-null values and fixed a bug in display (calling a proportion a percent). Could you check that this works?

**Comment by dscorbett** [comment]
This works. Thanks!
