### ISSUE TITLE
404 on download page

### ISSUE THREAD

**Issue by briancroxall** [mimno/Mallet#205]
When I go to the [download page](https://mimno.github.io/Mallet/download) for Mallet, I get a 404 error. 

Apologies if this issue tracker is not for the GitHub Pages site.

**Comment by mimno** [comment]
I redirected the nav bar link to the github resources page. Does that work, and is it clear what to do there? You need to scroll down a bit to see the links.

**Comment by briancroxall** [comment]
I think this works. I also realized after posting this issue that there's a download button on the main Mallet page that I had overlooked.
