### ISSUE TITLE
HierarchicalLDA can't be serialized

### ISSUE THREAD

**Issue by wojtuch** [mimno/Mallet#72]
Dear Mallet team,

I would like to ask if there is a design/functional reason behind not making `HierarchicalLDA` class not serializable?
Just like with the `ParallelTopicModel`, after I estimate the topics, I would like to be able to serialize it to disk for future use.

From what I see, just making `HierarchicalLDA` and `NCRPNode` implement `java.io.Serializable` would suffice.

I'd be very grateful if you could provide some explanation!
wojtuch

edit:
Unfortunately I'm unable to check if this modification has influence on the whole system as the tests (when building via maven) fail even on a freshly checked out project.
Nevertheless, this modification solves my issue and I can serialize the estimated model.
I can also make a pull request with my changes.

**Comment by brooksandrew** [comment]
+1

**Comment by wojtuch** [comment]
I guess it can be closed as PR #73 was accepted
