### ISSUE TITLE
The procedure of gaining topics of topic-unknown text using mallet in a java application

### ISSUE THREAD

**Issue by liuming-dev** [mimno/Mallet#87]
**Now I use eclipse as my programming ide, and I want to use Mallet in my java application to gain the exact  topics of a topic-unknown text ,but what is the procedure of the processing?** 

Here are my doubts:
1. Mallet needs to train the topic model first, so how to train it and what are the training data?
2. How to use the trained topic model to mining the topic from an topic-unknown text?

**Comment by Alias4bb** [comment]
Maybe this page can help you to solve the problem about how the Mallet trains the topic model and how to imort the training data .[Topic Modeling](http://mallet.cs.umass.edu/topics.php) that is all .
